### PR TITLE
DLS-9181: [FHDDS] Nested fieldsets in conditional reveal (EORI) [WCAG] - Initial splitting to three pages

### PR DESCRIPTION
**Pull request by drewmiley**

### CODE REVIEW

**Comment by drewmiley** [comment]
Current WIP screenshots
Screenshot 2024-03-14 at 13 55 11
Screenshot 2024-03-14 at 13 55 22
Screenshot 2024-03-14 at 13 55 29
Screenshot 2024-03-14 at 13 57 15

**Comment by drewmiley** [comment]
TODO: Need to test application submission works

**Comment by drewmiley** [comment]
Currently failing tests:

- [error] 	uk.gov.hmrc.fhregistrationfrontend.services.mapping.FormToDesSpecs
- [error] 	uk.gov.hmrc.fhregistrationfrontend.controllers.ImportingActivitiesControllerSpec
- [error] 	uk.gov.hmrc.fhregistrationfrontend.services.mapping.DesToFormSpec
- [error] 	uk.gov.hmrc.fhregistrationfrontend.controllers.ApplicationControllerSpec
- [error] 	uk.gov.hmrc.fhregistrationfrontend.actions.JourneyActionSpec
- [error] 	uk.gov.hmrc.fhregistrationfrontend.controllers.FormPageControllerSpec
- [error] 	uk.gov.hmrc.fhregistrationfrontend.services.mapping.DiffSpecs

**Comment by drewmiley** [comment]
TODO: Add ImportingActivitiesPageSpec in test/forms/journey

**Comment by drewmiley** [comment]
Screenshot 2024-04-02 at 15 46 12

**Review by BackRowOla — DISMISSED** [review]
Changes look good 👍

**Review by BackRowOla — APPROVED** [review]

**Pull request merged**
